name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build

    # Install Azure CLI
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # Login to Azure Container Registry
    - name: Login to ACR
      run: |
        echo "AmARxkvYkj2d4F383LMahYFaSsgVKtOZ4QBp8CxvJNvFRmAPBUydJQQJ99CDACGhslBEqg7NAAACAZCRAGF1" \
        | docker login myregistry1703.azurecr.io \
        -u myregistry1703 \
        --password-stdin

    - name: Build Docker image
      run: docker build -t ai-app:latest .

    - name: Tag image
      run: docker tag ai-app:latest myregistry1703.azurecr.io/ai-app:latest

    - name: Push image
      run: docker push myregistry1703.azurecr.io/ai-app:latest

    - name: Deploy to Azure
      run: |
        az login --service-principal \
          -u e3847b51-6f40-4576-adba-d48ee8d3d00b \
          -p i8z8Q~.RUpaRNuoYRw2oMxzYdv0tZvYx5xiJZbKO \
          --tenant 4a580e05-5259-4e06-bcb6-5b040159d260

        az containerapp update \
          --name my-ai-app \
          --resource-group MyResourceGroup \
          --image myregistry1703.azurecr.io/ai-app:latest

    - name: Health Check
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://my-ai-app.azurecontainerapps.io/health)
        if [ "$STATUS" -ne 200 ]; then
          echo "Deployment failed, rolling back"
          az containerapp revision set-active \
            --name my-ai-app \
            --resource-group MyResourceGroup \
            --revision previous
          exit 1
        fi